from dydx3.constants import API_HOST_GOERLI, API_HOST_MAINNET
from decouple import config

TOKEN_FACTOR_10 = ["XLM-USD","DOGE-USD","TRX-USD"]

# !!!! SELECT MODE !!!!
MODE = "DEVELOPMENT"
# DEVELOPMENT O PRODUCTION

# base and quote originali o invertite
VERSO_CONTRARIO = 1

# Close all open positions and orders
ABORT_ALL_POSITIONS = 0

# Find Cointegrated Pairs
FIND_COINTEGRATED = 1

# Manage Exits
MANAGE_EXITS = 1

# Place Trades
PLACE_TRADES = 1

SEND_STORICO_EMAIL = 0

# Resolution
RESOLUTION = "1HOUR"

# Stats Window
WINDOW = 21

# Thresholds - Opening
MAX_HALF_LIFE = 24
ZSCORE_THRESH = 1.5 #da riportare a 1.5
USD_PER_TRADE = 50
USD_MIN_COLLATERAL = 2000


# Thresholds - Closing
CLOSE_AT_ZSCORE_CROSS = True

# Ethereum Address
ETHEREUM_ADDRESS="0x889FfC589131b76Aa409493f8211FB74da3755ec"

# KEYS - PRODUCTION
# Must be on Mainnet in DYDX
STARK_PRIVATE_KEY_MAINNET = config("STARK_PRIVATE_KEY_MAINNET")
DYDX_API_KEY_MAINNET = config("DYDX_API_KEY_MAINNET")
DYDX_API_SECRET_MAINNET = config("DYDX_SECRET_MAINNET")
DYDX_API_PASSPHRASE_MAINNET = config("DYDX_API_PASSPHRASE_MAINNET")

# KEYS - DEVELOPMENT
# Must be on Testnet in DYDX
STARK_PRIVATE_KEY_TESTNET = config("STARK_PRIVATE_KEY_TESTNET")
DYDX_API_KEY_TESTNET = config("DYDX_API_KEY_TESTNET")
DYDX_API_SECRET_TESTNET =config("DYDX_SECRET_TESTNET")
DYDX_API_PASSPHRASE_TESTNET = config("DYDX_API_PASSPHRASE_TESTNET")

# KEYS - Export
STARK_PRIVATE_KEY = STARK_PRIVATE_KEY_MAINNET if MODE == "PRODUCTION" else STARK_PRIVATE_KEY_TESTNET
DYDX_API_KEY = DYDX_API_KEY_MAINNET if MODE == "PRODUCTION" else DYDX_API_KEY_TESTNET
DYDX_API_SECRET = DYDX_API_SECRET_MAINNET if MODE == "PRODUCTION" else DYDX_API_SECRET_TESTNET
DYDX_API_PASSPHRASE = DYDX_API_PASSPHRASE_MAINNET if MODE == "PRODUCTION" else DYDX_API_PASSPHRASE_TESTNET

# HOST - Export
HOST = API_HOST_MAINNET if MODE == "PRODUCTION" else API_HOST_GOERLI

# HTTP PROVIDER
HTTP_PROVIDER_MAINNET = "https://eth-mainnet.g.alchemy.com/v2/e5pO0uxxyEXEQkWU9GHPjSFxy5dnlcnZ"
HTTP_PROVIDER_TESTNET = "https://eth-goerli.g.alchemy.com/v2/TDF-WrPWLoMDxHIzICeHakUQyGx8Nken"
HTTP_PROVIDER = HTTP_PROVIDER_MAINNET if MODE == "PRODUCTION" else HTTP_PROVIDER_TESTNET